### PR TITLE
Add error handling to oauth authorizer

### PR DESCRIPTION
**Pull request by jake-billings**
If the OAuth authorizer fails for any reason (e.g. a token refresh call fails in a sovereign cloud), we have no way of diagnosing the issue.

This PR modifies the authorizer to record error messages so that we can debug this type of issue.

### CODE REVIEW

**Comment by shrutir25** [comment]
PR lgtm

**Comment by julienstroheker** [comment]
@jake-billings did you run `make generate` ?

**Review by julienstroheker — CHANGES_REQUESTED** [review]
see my comment

**Comment by jake-billings** [comment]
Done

**Review by julienstroheker — APPROVED** [review]

**Pull request merged**
